config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'

  devise_for :users
  resources :statuses
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  get 'jobs_all/:order', to: 'jobs#index'

  get 'jobs_filtered/:filter', to: 'jobs#index', as: :jobs_filtered


  get 'jobs_react', to: 'jobs#index_react', as: :jobs_react
  get 'appointments_react', to: 'appointments#index', as: :appointments_react



  devise_scope :user do
    get "/sign_out", to: "devise/sessions#destroy"
    get "/logout", to: "devise/sessions#destroy"
    get "/login", to: "devise/sessions#new"
    post "/login", to: "devise/sessions#create"
  end

  namespace :api do
    namespace :v1 do
      resources :jobs, only: [:index, :create, :destroy, :update]
    end
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :style, :link_style, :display_order)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :name %>  <span class="required"> *  </span> <br/>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :style %> <span class="required"> *  </span> <br/>
      <%= form.text_area :style %>
    </div>

    <div class="field">
      <%= form.label :link_style %> <span class="required"> *  </span> <br/>
      <%= form.text_area :link_style %>
    </div>


    <div class="field">
      <%= form.label :display_order %> <span class="required"> *  </span> <br/>
      <%= form.text_field :display_order %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary btn-small"%>
    </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Styling</th>
      <th>Link Styling</th>
      <th>Order</th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= status.style %></td>
        <td><%= status.link_style %></td>
        <td><%= status.display_order %></td>
        <td class="action_button"><%= link_to 'Show', status, :class => "btn btn-primary btn-small" %></td>
        <td class="action_button"><%= link_to 'Edit', edit_status_path(status),:class => "btn btn-primary btn-small"  %></td>
        <td class="action_button"><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-small"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path,  :class => "btn btn-primary btn-small"  %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>