config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'

  devise_for :users
  resources :statuses
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  get 'jobs_all/:order', to: 'jobs#index'

  get 'jobs_filtered/:filter', to: 'jobs#index', as: :jobs_filtered


  get 'jobs_react', to: 'jobs#index_react', as: :jobs_react
  get 'appointments_react', to: 'appointments#index', as: :appointments_react



  devise_scope :user do
    get "/sign_out", to: "devise/sessions#destroy"
    get "/logout", to: "devise/sessions#destroy"
    get "/login", to: "devise/sessions#new"
    post "/login", to: "devise/sessions#create"
  end

  namespace :api do
    namespace :v1 do
      resources :jobs, only: [:index, :create, :destroy, :update]
    end
  end

end

app/models/job.rb
class Job < ApplicationRecord

  validates_presence_of :company
  validates_presence_of :position
  validates_presence_of :status_id
  belongs_to :status

  scope :status_new, ->  { where(:status_id => Status.find_by_name("New").id) }

  scope :status_waiting_feedback, ->  { where(:status_id => Status.find_by_name("Waiting Feedback").id) }
  scope :status_submitted_info, ->  { where(:status_id => Status.find_by_name("Submitted Info").id) }
  scope :status_call_screen_scheduled, ->  { where(:status_id => Status.find_by_name("Call Screen Scheduled").id) }
  scope :status_interview_scheduled, ->  { where(:status_id => Status.find_by_name("Interview Scheduled").id) }
  scope :status_deactivated, ->  { where(:status_id => Status.find_by_name("Deactivated").id) }
  scope :status_dead_lead, ->  { where(:status_id => Status.find_by_name("Dead Lead").id) }
  scope :status_not_accepted, ->  { where(:status_id => Status.find_by_name("Not Accepted").id) }
  scope :status_hired, ->  { where(:status_id => Status.find_by_name("Hired").id) }
  scope :status_resigned, ->  { where(:status_id => Status.find_by_name("Resigned").id) }
  scope :status_code_sample_completed, -> { where(:status_id => Status.find_by_name("Code Sample Completed").id) }
  scope :status_waiting_interview_feedback, -> { where(:status_id => Status.find_by_name("Waiting interview feedback").id) }
  scope :status_pair_program_scheduled, -> { where(:status_id => Status.find_by_name("Pair-Program scheduled").id) }
  scope :status_job_on_hold, -> { where(:status_id => Status.find_by_name("Job on Hold").id) }




  def self.search(params)
    if params[:order]
      if params[:order] == "status"
        @jobs = Job.all.includes(:status).order("statuses.name #{params[:sort_order]}")
      else
        @jobs = Job.all.order("#{params[:order]} #{params[:sort_order]}")
      end
    elsif params[:search] && params[:search][:item]
      search_item = params[:search][:item].downcase
      @jobs = Job.where(
          "LOWER(company) LIKE '%#{search_item}%'
            OR LOWER(recruiter) LIKE '%#{search_item}%'
            OR LOWER(recruiter_email) LIKE '%#{search_item}%'
            OR LOWER(recruiter_phone) LIKE '%#{search_item}%'
            OR LOWER(company_website) LIKE '%#{search_item}%'
            OR LOWER(company_address) LIKE '%#{search_item}%'
            OR LOWER(company_contact) LIKE '%#{search_item}%'
            OR LOWER(company_phone) LIKE '%#{search_item}%'
            OR LOWER(position) LIKE '%#{search_item}%'
            OR LOWER(comments) LIKE '%#{search_item}%'
            "
      ).order("status_id ASC")
    else
      @jobs = Job.all.order("status_id ASC")
    end
    if params[:filter]
      filter = params[:filter]
      if filter.include?("%20")
        filter = filter.gsub("%20" ," ")
      end
      case filter
        when "New"
          @jobs = @jobs.status_new
        when "Waiting Feedback"
          @jobs = @jobs.status_waiting_feedback
        when "Submitted Info"
          @jobs = @jobs.status_submitted_info
        when  "Call Screen Scheduled"
          @jobs = @jobs.status_call_screen_scheduled
        when "Interview Scheduled"
          @jobs = @jobs.status_interview_scheduled
        when "Deactivated"
          @jobs = @jobs.status_deactivated
        when "Dead Lead"
          @jobs = @jobs.status_dead_lead
        when "Not Accepted"
          @jobs = @jobs.status_not_accepted
        when "Hired"
          @jobs = @jobs.status_hired
        when "Resigned"
          @jobs = @jobs.status_resigned
        when "Code Sample Completed"
          @jobs = @jobs.status_code_sample_completed
        when "Waiting interview feedback"
          @jobs = @jobs.status_waiting_interview_feedback
        when "Pair-Program scheduled"
          @jobs = @jobs.status_pair_program_scheduled
        when "Job on Hold"
          @jobs = @jobs.status_job_on_hold
      end

    end
    @jobs
  end
end

app/controllers/api/v1/jobs_controller.rb
class Api::V1::JobsController < Api::V1::BaseController
  def index
    respond_with Job.all
  end

  def create
    respond_with :api, :v1, Job.create(job_params)
  end

  def destroy
    respond_with Job.destroy(params[:id])
  end

  def update
    job = Job.find(params["id"])
    item.update_attributes(job_params)
    respond_with job, json: job
  end

  private
  def job_params
    params.require(:job).permit(:id, :company, :recruiter, :recruiter_email, :recruiter_phone, :recruiter_cell, :last_contact,
                                :company_website, :position, :company_contact, :company_phone, :company_address, :status_id )
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
    #set up logic for the order links (ASC/DESC)
    if session[:sort_order].blank?
      session[:sort_order] = "ASC"
    else
      case session[:sort_order]
        when "ASC"
          session[:sort_order] = "DESC"
        when "DESC"
          session[:sort_order] = "ASC"
      end
    end
    @selected_status = params[:filter]
    @selected_status = "All" if @selected_status.blank?
    @jobs = Job.search(params.merge(:sort_order => session[:sort_order], :filter => @selected_status))
    @statuses = Status.all.order("display_order ASC")
    respond_to do |format|
      format.html { render :index}
      format.json {render @jobs.to_json, status: :ok}
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :recruiter, :recruiter_email, :last_contact, :recruiter_phone, :recruiter_cell, :company_website, :company_address, :company_contact, :company_phone, :position, :comments, :status_id)

    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def set_class(job)
    Status.find(job.status).name.gsub(" ", "-").downcase
  end

  def get_job_count(status)
    Job.where(status_id: status.id).count
  end
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <table>
      <tr>
        <td>
          <div class="field">
            <%= f.label :company %>  <span class="required"> *  </span> <br/>
            <%= f.text_field :company, class: "job_edit_field" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :recruiter %><br/>
            <%= f.text_field :recruiter, class: "job_edit_field" %>
          </div>
        </td>
      </tr>

      <tr>
        <td>
          <div class="field">
            <%= f.label :recruiter_email %><br/>
            <%= f.text_field :recruiter_email, class: "job_edit_field" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :recruiter_phone %><br/>
            <%= f.text_field :recruiter_phone, class: "job_edit_field" %>
          </div>
        </td>
      </tr>

      <tr>
        <td>
          <div class="field">
            <%= f.label :recruiter_cell %><br/>
            <%= f.text_field :recruiter_cell, class: "job_edit_field" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :last_contact %><br/>
            <input type="text" name="job[last_contact]", class="job_edit_field" value=<%= @job.last_contact.blank? ? Time.now.to_date :  @job.last_contact.to_date%> data-behaviour='datepicker' data-date-format='yyyy/mm/dd' >
          </div>
        </td>
      </tr>

      <tr>
        <td>
          <div class="field">
            <%= f.label :company_website %><br/>
            <%= f.text_field :company_website, class: "job_edit_field" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :position %> <span class="required"> *  </span> <br/>
            <%= f.text_field :position, class: "job_edit_field" %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="field">
            <%= f.label :company_contact %><br/>
            <%= f.text_field :company_contact, class: "job_edit_field" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :company_phone %><br/>
            <%= f.text_field :company_phone, class: "job_edit_field" %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="field">
            <%= f.label :company_address %><br/>
            <%= f.text_area :company_address, class: "job_edit_field" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :status_id %>  <span class="required"> *  </span> <br/>
            <%= f.select(:status_id, Status.all.collect{|s| [s.name, s.id]})%>
          </div>
        </td>
      </tr>
    </table>

    <div class="field">
      <%= f.label :comments %><br/>
      <%= f.text_area :comments, class: "comments job_edit_field"%>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary btn-small"%>
    </div>

    <script type="text/javascript">
        //set up the date picker here, since it wouldn't load reliable in coffee script files
        $(document).ready(function(){
            $('[data-behaviour~=datepicker]').datepicker({
                autoclose: true
            });
            $(".comments").jqte();
        })
    </script>

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h1>Job Tracker</h1>

    <div class="actions">
      <%= link_to 'New Job', new_job_path, class: "btn btn-primary btn-small" %>
    </div>

    <!-- <p>Color Key</p> -->
      <% status_selections = [] %>
      <% status_selections << ["All",  jobs_path] %>
      <% @statuses.each do |status| %>
        <% job_count = get_job_count(status) %>
        <% status_selections << ["#{status.name}  (#{job_count.to_s})",  jobs_filtered_path(filter: status.name) ] %>
      <% end %>

    <% if params[:filter] %>
        <% filter = params[:filter] %>
        <%   if filter.include?("%20") %>
            <%filter = filter.gsub("%20" ," ") %>
        <% end %>
    <% end %>

    <div class="row-fluid">
      <label>Filter by Status: </label>
      <% if params[:filter] %>
          <%= select "jobs_select", "id", status_selections, {:selected => [filter, jobs_filtered_path],  include_blank: false } %>
      <% else %>
          <%= select "jobs_select", "id", status_selections, {include_blank: false } %>
      <% end %>
    </div>

    <br/>
    <% filter_link = params[:filter].blank? ? '' : '?filter=' + params[:filter]%>

    <p> Showing results for:  <b><%= @selected_status %></b>  </p>
    <% if @jobs.blank? %>
        <p>No Matching Jobs! </p>
    <% else %>
        <div class="jobs-table">
          <table class="table">
            <thead>
            <tr>
              <th><%= link_to "Company", '/jobs_all/company' + filter_link %></th>
              <th><%= link_to "Recruiter", '/jobs_all/recruiter'  + filter_link%></th>
              <th><%= link_to "Last contact", '/jobs_all/last_contact'  + filter_link%></th>
              <th><%= link_to "Status", '/jobs_all/status'  + filter_link%></th>
              <th colspan="3" style="text-align: center;">Actions</th>
            </tr>
            </thead>

            <tbody>
            <% @jobs.each do |job| %>
                <tr>
                  <td style="<%= job.status.try('style')  %>" > <%= link_to job.company, job, {style: job.status.try('link_style')}  %></td>
                  <td><%= job.recruiter[0..20] unless job.recruiter.blank? %></td>
                  <td class="last-contact"><%= job.last_contact unless job.last_contact.blank? %></td>
                  <td><%= job.status.try('name') %></td>
                  <td><%= link_to 'Show', job, class: "btn btn-primary btn-small" %></td>
                  <td><%= link_to 'Edit', edit_job_path(job), class: "btn btn-primary btn-small" %></td>
                  <td><%= link_to 'Destroy', job, class: "btn btn-primary btn-small", method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
    <br>
    <div class="actions">
      <%= link_to 'New Job', new_job_path, class: "btn btn-primary btn-small" %>
    </div>
  </div>
  <script>
      $('#jobs_select_id').bind('change', function() { window.location.pathname = $(this).val() });
  </script>

app/views/jobs/index_react.html.erb
<h1> Greeting </h1>



<%= react_component('HelloWorld',  {prerender: true, greeting: 'Hello out there!'}) %>

app/views/jobs/new.html.erb
<div class="col-md-12">
  <h1>New job</h1>

  <%= render 'form', job: @job  %>
  <div class="actions">
    <%= button_to 'Back', jobs_path, class: "btn btn-primary btn-small"  %>
  </div>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Job </h1>

<div class="col-md-12" style="margin-bottom: 20px;">
  <table>
    <tr>
      <th>Company</th> <td><%= @job.company %></td>
    </tr>
    <tr>
      <th>Recruiter</th><td><%= @job.recruiter %></td>
    </tr>
    <tr>
      <th>Email</th> <td><%= @job.recruiter_email %></td>
    </tr>
    <tr>
      <th>Last Contact</th> <td><%= @job.last_contact.strftime("%m-%d-%Y") unless @job.last_contact.blank? %></td>
    </tr>
    <tr>
      <th>Phone</th><td><%= @job.recruiter_phone %></td>
    </tr>
    <tr>
      <th>Cell</th><td><%= @job.recruiter_cell %></td>
    </tr>
    <tr>
      <th>Website</th> <td><%= @job.company_website %></td>
    </tr>
    <tr>
      <th>Address</th><td><%= @job.company_address %></td>
    </tr>
    <tr>
      <th>Contact</th><td><%= @job.company_contact %></td>
    </tr>
    <tr>
      <th>Phone</th> <td><%= @job.company_phone %></td>
    </tr>
    <tr>
      <th>Position</th><td><%= @job.position %></td>
    </tr>
    <tr>
      <th>Status</th><td> <%= Status.find(@job.status.id).name %></td>
    </tr>
    <tr>
      <th>Comments</th>
    </tr>
    <tr>
      <td colspan="2"><%= @job.comments.html_safe unless @job.comments.blank? %></td>
    </tr>
  </table>
</div>




<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-primary btn-small" %> |
<%= link_to 'Back', jobs_path, class: "btn btn-primary btn-small" %>