config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'

  devise_for :users
  resources :statuses
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  get 'jobs_all/:order', to: 'jobs#index'

  get 'jobs_filtered/:filter', to: 'jobs#index', as: :jobs_filtered


  get 'jobs_react', to: 'jobs#index_react', as: :jobs_react
  get 'appointments_react', to: 'appointments#index', as: :appointments_react



  devise_scope :user do
    get "/sign_out", to: "devise/sessions#destroy"
    get "/logout", to: "devise/sessions#destroy"
    get "/login", to: "devise/sessions#new"
    post "/login", to: "devise/sessions#create"
  end

  namespace :api do
    namespace :v1 do
      resources :jobs, only: [:index, :create, :destroy, :update]
    end
  end

end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <%= nav_bar :fixed => :top  do %>

      <%= menu_group do %>

          <% if current_user.blank? %>
              <%= menu_item "User Login", login_path %>
          <% else %>
              <%= menu_item "Jobs", jobs_path %>
              <%= menu_item "Statuses", statuses_path %>
              <%= menu_item "Logout", sign_out_path %>
          <% end %>
      <% end %>
  <% end %>
</div>

app/views/layouts/_search_form.html.erb
<div class="col-md-12">
  <%= form_for("search", :url => "/jobs", :method => :get) do |f| %>
      <div class="form-group col-md-6">
        <%= f.text_field "item", class:'form-control input-normal' %>
      </div>
      <div class="form-group col-md-3">
      <span id="search_button">
        <%= f.submit  "Search Jobs", class: "btn btn-primary btn-small", style: "margin-top: 9px;"%>
      </span>
      </div>
  <% end %>
</div>
<div style="clear: both;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'layouts/nav' %>




<div class="container-fluid">
  <div class="row-fluid">
    <%= bootstrap_flash %>
    <%= render :partial => "layouts/search_form" %>
    <%= yield %>
  </div>
  <div style="clear: both;"></div>
  <footer>
    <p>&copy; John Kropka 2014-2018</p>
    <div class="fright"> This website is running <b>Rails: <%= Rails::VERSION::STRING %></b> </div>
  </footer>
</div>
</body>
</html>